swagger: "2.0"
info:
  description: "This API classifies molecules as proteins, carbohydrates or lipids based on the \"weight\" of the molecule. Molecules with weights that are multiples of 3 shall be classified as proteins. Molecules with weights that are multiples of 5 shall be classified as carbohydrates. Molecules with weights that are both multiples of both 3 and 5 shall be classified as lipids. In any other case the molecule shall be classified as a nucleic acid."
  version: "1.0.0"
  title: "Molecule Classifier"
  termsOfService: "https://www.gsk.com/en-gb/terms-of-use/"
  contact:
    email: "odean.x.maye@gsk.com"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
paths:
  /molecule/classify:
    post:
      tags:
      - "molecule"
      summary: "Classify a molecule"
      description: ""
      operationId: "classifyMolecule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Molecule object to be classified"
        required: true
        schema:
          $ref: "#/definitions/Molecule"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Molecule"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/ApiFailureResponse"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiFailureResponse"
definitions:
  Molecule:
    type: "object"
    required:
    - "weight"
    properties:
      weight:
        type: "integer"
        format: "int64"
      type:
        type: "string"
        description: "Molecule Type"
        enum:
        - "PROTEIN"
        - "LIPID"
        - "CARBOHYDRATE"
        - "NUCLEIC ACID"
  ApiFailureResponse:
    type: "object"
    properties:
      message:
        type: "string"
        enum:
        - "CLIENT ERROR"
        - "SERVER ERROR"
externalDocs:
  description: "GSK Software Engineering Careers"
  url: "https://www.gsk.com/en-gb/careers/careers-search/?q=software%20engineer"